name: SLATE Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    uses: slateci/github-actions/.github/workflows/slate-deployment.yml@develop
    with:
      mailgun_send_to: "adam.h.griffith@utah.edu"
    secrets:
      mailgun_api_key: "${{ secrets.MAILGUN_API_KEY }}"
      slate_api_token: "${{ secrets.SLATE_API_TOKEN }}"
