name: SLATE Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    uses: slateci/github-actions/.github/workflows/slate-deployment.yml@feature/6_add-slate-instance-gitops
    with:
      email_changes: false
    secrets:
      slate_api_token: ${{ secrets.SLATE_API_TOKEN }}
