name: SLATE Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Pull down automation script
        run: curl -fsSL https://raw.githubusercontent.com/slateci/gitops-automation-script/main/PushUpdates.py -o PushUpdates.py

      - name: Install Python dependencies
        run: pip install -U requests

      - name: Deploy to SLATE
        id: deploy
        run: |
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.event.after }}"

          # https://stackoverflow.com/questions/40883798/how-to-get-git-diff-of-the-first-commit
          if [[ $BEFORE = "0000000000000000000000000000000000000000" ]]; then
            BEFORE="4b825dc642cb6eb9a060e54bf8d69288fbee4904"
          fi

          if [[ $AFTER = "0000000000000000000000000000000000000000" ]]; then
            AFTER="4b825dc642cb6eb9a060e54bf8d69288fbee4904"
          fi

          git diff --name-status --pretty="format:" "$BEFORE" "$AFTER" > .changed
          echo "::set-output name=DIFF_OUTPUT::$(git diff "$BEFORE" "$AFTER")"
          python3 PushUpdates.py ".changed" "${{ secrets.SLATE_API_TOKEN }}"
          rm .changed

      # Uncomment this out if you'd like Mailgun notifications.
      # - name: Email Changes
      #   if: ${{ steps.deploy.outputs.push == 'true' }}
      #   run: >-
      #     echo -n "$MAILGUN_SEND_TO"
      #     | xargs -r -d',' printf -- '-F to="%s"\0'
      #     | xargs -r0
      #     curl -s --user "api:${MAILGUN_API_KEY}"
      #     https://api.mailgun.net/v3/${MAILGUN_DOMAIN}/messages
      #     -F from="$MAILGUN_FROM"
      #     -F subject="$MAILGUN_SUBJECT"
      #     -F text="Here's the diff of changes made:\n\n${MAILGUN_BODY}"
      #   env:
      #     MAILGUN_SUBJECT: "SLATE GitOps Change Summary"
      #     MAILGUN_BODY: "${{ steps.deploy.outputs.DIFF_OUTPUT }}"
      #     # fill these out appropriately
      #     MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
      #     MAILGUN_DOMAIN: foo.edu
      #     MAILGUN_FROM: "Foo Bar <bar@foo.edu>"
      #     # this can be a comma delimited list
      #     MAILGUN_SEND_TO: foo@bar.com,hello@world.com

      - name: Commit SLATE Instance ID
        if: ${{ steps.deploy.outputs.push == 'true' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "append new SLATE instance ID" --allow-empty
          git push
